### ISSUE TITLE
Using MenuView as UIBarButtonItem

### ISSUE THREAD

**Issue by victorBaro** [TwoLivesLeft/Menu#10]
Congratulations on the menu, it looks stunning and I believe this should be a standard UIKit control.

I have been playing with it in one of my apps and tried to add it to the navigation bar as UIBarButtonItem. The menu shows up correctly and it opens up as it should when tapping on it. However, it does not let you select any option.  

This is because options are outside its superview(navbar) bounds. I am guessing I could override hittest and point(inside:), I haven't tried it yet. I just wanted to ask if I am missing something or this is the only way to go.

Thank you,

**Comment by victorBaro** [comment]
This is an example: 
<img width="744" alt="screenshot 2019-01-16 at 12 22 14" src="https://user-images.githubusercontent.com/994334/51269966-c3f3d500-1991-11e9-863a-0a678e4fc7d6.png">

**Comment by victorBaro** [comment]
I am not very proud of this code, but it works. I created a custom navigation bar and added this code:

```swift
    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        if let menuView = findMenuView(in: self) {
            let newPoint = convert(point, to: menuView)
            if let view = menuView.hitTest(newPoint, with: event) { return view }
        }
        return super.hitTest(point, with: event)
    }
    
    override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        if let menuView = findMenuView(in: self) {
            let newPoint = convert(point, to: menuView)
            if menuView.point(inside: newPoint, with:event) { return true }
        }
        return super.point(inside: point, with: event)
    }
    
    private func findMenuView(in view: UIView) -> MenuView? {
        if let found = view as? MenuView { return found }
        
        for subview in view.subviews {
            if let menuView = findMenuView(in: subview) { return menuView }
        }
        return nil
    }
```

If anyone has a better way around, I would appreciate. I don't really like to have a custom navbar that knows about the menu view.

**Comment by simsaens** [comment]
Your app looks really nice

I think the custom hit testing is the way to go, but why not have your custom nav bar take a closure that returns the UIView its interested in hit testing? That way it doesn't need to know about the menu view.

    var viewForHitException: () -> UIView? = { return nil }

Then in your `hitTest(_:with:)` and `point(inside:with:)` methods you could request the view from the closure which has been assigned by whatever should know about both the menu and the nav bar.

It's still the same thing but at least then your nav bar doesn't need to be coupled to the menu bar.

**Comment by victorBaro** [comment]
Thank you for your quick reply. I will do that :+1:

**Comment by victorBaro** [comment]
And the app is [Panels](https://itunes.apple.com/us/app/panels-comic-reader/id1236567663?mt=8) a comic reader for iOS. I have a couple of places where I want to include your menu :)

**Comment by aaronpearce** [comment]
Great solution! I've hit the same issue, but I'm using multiple MenuViews at once. I'm working off your concept above now to see if I can get it working with multiple.

**Comment by simsaens** [comment]
@aaronpearce I was going to suggest in my initial comment to use

    var viewsForHitException: () -> [UIView] = { return [] }

As the closure style, then you'd probably want to return the first positive hitTest result?

**Comment by aaronpearce** [comment]
Made my solution into a basic UINavigationBar extension as I'm using it throughout my app so had to resort to associated objects to store the views for hit exception. A subclass could make it tidier. Hope it helps.

```
extension UINavigationBar {
    
    private struct AssociatedKeys {
        static var viewsForHitException = "menu_viewsForHitException"
    }
    
    typealias ViewsForHitExceptionClosure = () -> [UIView]
    var viewsForHitException: ViewsForHitExceptionClosure {
        get {
            return objc_getAssociatedObject(self, &AssociatedKeys.viewsForHitException) as? ViewsForHitExceptionClosure ?? { [] }
        }
        
        set {
            objc_setAssociatedObject(self, &AssociatedKeys.viewsForHitException, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }
    
    override open func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        for hitExpectionView in viewsForHitException() {
            let newPoint = convert(point, to: hitExpectionView)
            if hitExpectionView.hitTest(newPoint, with: event) != nil {
                return hitExpectionView
            }
        }
        return super.hitTest(point, with: event)
    }
    
    override open func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        for hitExpectionView in viewsForHitException() {
            let newPoint = convert(point, to: hitExpectionView)
            if hitExpectionView.point(inside: newPoint, with:event) {
                return true
            }
        }
        return super.point(inside: point, with: event)
    }
}
```

**Comment by AMJ-7** [comment]
> Made my solution into a basic UINavigationBar extension as I'm using it throughout my app so had to resort to associated objects to store the views for hit exception. A subclass could make it tidier. Hope it helps.
> 
> ```
> extension UINavigationBar {
>     
>     private struct AssociatedKeys {
>         static var viewsForHitException = "menu_viewsForHitException"
>     }
>     
>     typealias ViewsForHitExceptionClosure = () -> [UIView]
>     var viewsForHitException: ViewsForHitExceptionClosure {
>         get {
>             return objc_getAssociatedObject(self, &AssociatedKeys.viewsForHitException) as? ViewsForHitExceptionClosure ?? { [] }
>         }
>         
>         set {
>             objc_setAssociatedObject(self, &AssociatedKeys.viewsForHitException, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
>         }
>     }
>     
>     override open func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
>         for hitExpectionView in viewsForHitException() {
>             let newPoint = convert(point, to: hitExpectionView)
>             if hitExpectionView.hitTest(newPoint, with: event) != nil {
>                 return hitExpectionView
>             }
>         }
>         return super.hitTest(point, with: event)
>     }
>     
>     override open func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
>         for hitExpectionView in viewsForHitException() {
>             let newPoint = convert(point, to: hitExpectionView)
>             if hitExpectionView.point(inside: newPoint, with:event) {
>                 return true
>             }
>         }
>         return super.point(inside: point, with: event)
>     }
> }
> ```

how to use it pls .
